import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useP } from '../../lib/store.jsx';
import { Card, PageHead, Empty } from '../../../components/ui.jsx';
import { When } from '../../components/common.jsx';

// Email and Teams messages generated by notifications, reminders, escalations and digests (WF-11, WF-12).
export default function Outbox() {
  const { query, view, me, dispatch } = useP();
  const [items, setItems] = useState([]);
  const [channel, setChannel] = useState('');
  const [open, setOpen] = useState(null);
  useEffect(() => { query('outbox', {}).then((r) => setItems([...(r || [])].reverse())); }, [view.version]); // eslint-disable-line react-hooks/exhaustive-deps
  const shown = items.filter((m) => !channel || m.channel === channel);
  const admin = me.roles.includes('admin');
  return (
    <div className="stack">
      <PageHead eyebrow="Administration" title="Notification outbox" actions={admin && <button className="btn" onClick={() => dispatch('jobs.run', {}, { success: 'Reminders, escalations and digests run' })}>Run daily jobs now</button>}>
        {admin ? 'All messages the platform has sent or queued.' : 'Messages sent to you.'} Email is delivered through Microsoft Graph and Teams cards through the Teams connector when those are connected.
      </PageHead>
      <div className="filters">
        <select value={channel} onChange={(e) => setChannel(e.target.value)} aria-label="Channel"><option value="">All channels</option><option value="email">Email</option><option value="teams">Teams</option></select>
        <span className="muted small">{shown.length} messages · daily jobs last run {view.jobs?.digest || 'never'}</span>
      </div>
      {shown.length ? (
        <Card pad={false}>
          {shown.slice(0, 300).map((m) => (
            <div key={m.id} className="notif" role="button" tabIndex={0} onClick={() => setOpen(open === m.id ? null : m.id)}>
              <div className="row" style={{ justifyContent: 'space-between' }}>
                <span className="small"><span className={`pill ${m.channel === 'teams' ? 'navy' : ''}`}>{m.channel === 'teams' ? 'Teams' : 'Email'}</span> <strong>{m.subject}</strong></span>
                <span className="mini"><When at={m.at} /></span>
              </div>
              <div className="mini">To {m.toName} &lt;{m.to}&gt;{m.digest ? ' · daily digest' : ''}</div>
              {open === m.id && (
                <div style={{ marginTop: 8 }}>
                  {m.card ? (
                    <div className="teams-card">
                      <div className="tc-head"><span className="tc-app">CTO Proposals</span><span className="mini">Adaptive card</span></div>
                      <div className="tc-body"><div className="strong">{m.subject}</div><dl className="kv" style={{ gridTemplateColumns: '110px 1fr', marginTop: 6 }}>{m.card.facts.map(([k, v]) => [<dt key={`${k}t`}>{k}</dt>, <dd key={`${k}d`}>{v}</dd>])}</dl></div>
                      <div className="tc-actions"><Link className="btn btn-sm btn-primary" to={`/bids/${m.card.bidId}/approvals`}>Approve…</Link><Link className="btn btn-sm" to={`/bids/${m.card.bidId}/approvals`}>Reject…</Link></div>
                    </div>
                  ) : <pre className="small" style={{ whiteSpace: 'pre-wrap', margin: 0, fontFamily: 'inherit' }}>{m.text}</pre>}
                  {m.link && <div className="mini" style={{ marginTop: 6 }}>Link: <Link to={m.link}>{m.link}</Link></div>}
                </div>
              )}
            </div>
          ))}
        </Card>
      ) : <Empty title="No messages">Notifications generate email and Teams messages here.</Empty>}
    </div>
  );
}
